"""add open_days to locations

Revision ID: b7a5c08978be
Revises: 6d7546e47693
Create Date: 2026-01-19 19:22:53.955691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a5c08978be'
down_revision: Union[str, Sequence[str], None] = '6d7546e47693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnosticos')
    op.drop_table('consejos')
    op.alter_column('bot_logos', 'bot_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('bot_logos', 'logo_header_1',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('bot_logos', 'logo_header_2',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('bot_logos', 'logo_signature',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(None, 'bot_logos', type_='foreignkey')
    op.alter_column('bots', 'doctor_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bots', 'token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bots', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('citas', 'user_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('citas', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('citas', 'fecha',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('citas', 'hora',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('citas', 'ubicacion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('citas', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('citas', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('citas', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_citas_fecha_status'), table_name='citas')
    op.drop_index(op.f('idx_citas_reminder'), table_name='citas')
    op.drop_index(op.f('idx_citas_usuario_activo'), table_name='citas')
    op.drop_constraint(None, 'citas', type_='foreignkey')
    op.create_foreign_key(None, 'citas', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('extra_modules', 'module_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('extra_modules', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('extra_modules', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint('uq_doctor_module', 'extra_modules', ['doctor_id', 'module_name'])
    op.alter_column('faqs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'faqs', type_='foreignkey')
    op.create_foreign_key(None, 'faqs', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('gallery', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('gallery', 'media_file_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('gallery', 'media_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('gallery', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'gallery', type_='foreignkey')
    op.create_foreign_key(None, 'gallery', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.add_column('locations', sa.Column('open_days', sa.String(), nullable=True))
    op.alter_column('locations', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('locations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('main_menu_buttons', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('main_menu_buttons', 'callback_data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('main_menu_buttons', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'main_menu_buttons', type_='foreignkey')
    op.create_foreign_key(None, 'main_menu_buttons', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('medical_histories', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medical_histories', 'history_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('medical_histories', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('medical_histories', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('medical_histories', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_foreign_key(None, 'medical_histories', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('medical_histories', 'sexual_pain_dyspareunia')
    op.drop_column('medical_histories', 'gastro_symptoms_during_period')
    op.drop_column('medical_histories', 'leg_pain_zone')
    op.drop_column('medical_histories', 'habits_urinary')
    op.drop_column('medical_histories', 'sexual_pain_scale')
    op.drop_column('medical_histories', 'bowel_dischezia_scale')
    op.drop_column('medical_histories', 'gastro_symptoms_before_period')
    op.drop_column('medical_histories', 'sexual_pain_type')
    op.drop_column('medical_histories', 'bowel_dischezia')
    op.drop_column('medical_histories', 'urinary_nocturia')
    op.drop_column('medical_histories', 'urinary_incontinence')
    op.drop_column('medical_histories', 'urinary_irritation')
    op.drop_column('medical_histories', 'leg_pain_type')
    op.drop_column('medical_histories', 'bowel_frequency')
    op.drop_column('medical_histories', 'urinary_pain_scale')
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('notifications', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_foreign_key(None, 'notifications', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pdf_settings', 'setting_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('pdf_settings', 'setting_value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('pdf_settings', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_foreign_key(None, 'pdf_settings', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.alter_column('precios', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('precios', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'precios', type_='foreignkey')
    op.create_foreign_key(None, 'precios', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('submenu_buttons', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('submenu_buttons', 'callback_data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('submenu_buttons', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('submenus', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('submenus', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('submenus', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'submenus', type_='foreignkey')
    op.create_foreign_key(None, 'submenus', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('test_questions', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('test_questions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.create_foreign_key(None, 'test_questions', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('text_content', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(None, 'text_content', type_='foreignkey')
    op.create_foreign_key(None, 'text_content', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_actions', 'action_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_actions', 'action_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'text_content', type_='foreignkey')
    op.create_foreign_key(None, 'text_content', 'bots', ['bot_id'], ['id'])
    op.alter_column('text_content', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.create_foreign_key(None, 'test_questions', 'bots', ['bot_id'], ['id'])
    op.alter_column('test_questions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('test_questions', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'submenus', type_='foreignkey')
    op.create_foreign_key(None, 'submenus', 'bots', ['bot_id'], ['id'])
    op.alter_column('submenus', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('submenus', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('submenus', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('submenu_buttons', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('submenu_buttons', 'callback_data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('submenu_buttons', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'precios', type_='foreignkey')
    op.create_foreign_key(None, 'precios', 'bots', ['bot_id'], ['id'])
    op.alter_column('precios', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('precios', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'pdf_settings', type_='foreignkey')
    op.alter_column('pdf_settings', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('pdf_settings', 'setting_value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('pdf_settings', 'setting_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('medical_histories', sa.Column('urinary_pain_scale', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('bowel_frequency', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('leg_pain_type', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('urinary_irritation', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('urinary_incontinence', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('urinary_nocturia', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('bowel_dischezia', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('sexual_pain_type', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('gastro_symptoms_before_period', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('bowel_dischezia_scale', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('sexual_pain_scale', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('habits_urinary', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('leg_pain_zone', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('gastro_symptoms_during_period', sa.TEXT(), nullable=True))
    op.add_column('medical_histories', sa.Column('sexual_pain_dyspareunia', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'medical_histories', type_='foreignkey')
    op.alter_column('medical_histories', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('medical_histories', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('medical_histories', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('medical_histories', 'history_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('medical_histories', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'main_menu_buttons', type_='foreignkey')
    op.create_foreign_key(None, 'main_menu_buttons', 'bots', ['bot_id'], ['id'])
    op.alter_column('main_menu_buttons', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('main_menu_buttons', 'callback_data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('main_menu_buttons', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'bots', ['bot_id'], ['id'])
    op.alter_column('locations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('locations', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('locations', 'open_days')
    op.drop_constraint(None, 'gallery', type_='foreignkey')
    op.create_foreign_key(None, 'gallery', 'bots', ['bot_id'], ['id'])
    op.alter_column('gallery', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('gallery', 'media_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('gallery', 'media_file_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('gallery', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'faqs', type_='foreignkey')
    op.create_foreign_key(None, 'faqs', 'bots', ['bot_id'], ['id'])
    op.alter_column('faqs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_doctor_module', 'extra_modules', type_='unique')
    op.alter_column('extra_modules', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('extra_modules', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('extra_modules', 'module_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'citas', type_='foreignkey')
    op.create_foreign_key(None, 'citas', 'bots', ['bot_id'], ['id'])
    op.create_index(op.f('idx_citas_usuario_activo'), 'citas', ['user_id', 'bot_id', 'status'], unique=False)
    op.create_index(op.f('idx_citas_reminder'), 'citas', ['bot_id', 'status', 'reminder_sent'], unique=False)
    op.create_index(op.f('idx_citas_fecha_status'), 'citas', ['bot_id', 'fecha', 'status'], unique=False)
    op.alter_column('citas', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('citas', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('citas', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('citas', 'ubicacion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('citas', 'hora',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('citas', 'fecha',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('citas', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('citas', 'user_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bots', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('bots', 'token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bots', 'doctor_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(None, 'bot_logos', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bot_logos', 'logo_signature',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bot_logos', 'logo_header_2',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bot_logos', 'logo_header_1',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bot_logos', 'bot_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('consejos',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('bot_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosticos',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('bot_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('image_file_id', sa.TEXT(), nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
