# features/preconsultas_admin/states.py

(
    AWAITING_PHYSICAL_EXAM,
    AWAITING_ULTRASOUND,
    AWAITING_DIAGNOSIS,
    ADDING_DIAGNOSIS_ITEM,
    AWAITING_PLAN,
    ADDING_PLAN_ITEM,
    AWAITING_OBSERVATIONS,
    AWAITING_EXAM_INPUT,
    AWAITING_EXAM_TEMPLATE_CHOICE

) = range(200, 209)